"""add_shop_logistics_defaults

Revision ID: 64d5567556a0
Revises: 371f2ecb8f79
Create Date: 2026-04-23 10:00:17.603871
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d5567556a0'
down_revision: Union[str, None] = '371f2ecb8f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('np_default_volume_m3', sa.Float(), nullable=False, server_default='0.004'))
    op.add_column('shops', sa.Column('np_default_payer_type', sa.String(length=20), nullable=False, server_default='Sender'))
    op.add_column('shops', sa.Column('np_default_payment_method', sa.String(length=20), nullable=False, server_default='Cash'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'np_default_payment_method')
    op.drop_column('shops', 'np_default_payer_type')
    op.drop_column('shops', 'np_default_volume_m3')
    # ### end Alembic commands ###
