"""add_np_sender_caching_fields

Revision ID: 990470ad5d99
Revises: 64d5567556a0
Create Date: 2026-04-23 11:07:59.436966
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990470ad5d99'
down_revision: Union[str, None] = '64d5567556a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('np_sender_ref', sa.String(length=36), nullable=True))
    op.add_column('shops', sa.Column('np_sender_contact_ref', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'np_sender_contact_ref')
    op.drop_column('shops', 'np_sender_ref')
    # ### end Alembic commands ###
