"""add_product_catalog_and_packaging

Revision ID: bd752467a39b
Revises: 990470ad5d99
Create Date: 2026-04-23 14:26:02.778663
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd752467a39b'
down_revision: Union[str, None] = '990470ad5d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_boxes',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('packaging_type', sa.Enum('BOX', 'ENVELOPE', name='packaging_type', create_constraint=True), nullable=False),
    sa.Column('inner_length_mm', sa.Integer(), nullable=False),
    sa.Column('inner_width_mm', sa.Integer(), nullable=False),
    sa.Column('inner_height_mm', sa.Integer(), nullable=False),
    sa.Column('max_thickness_mm', sa.Integer(), nullable=True),
    sa.Column('max_weight_g', sa.Integer(), nullable=False),
    sa.Column('tare_weight_g', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_boxes_packaging_type'), 'packaging_boxes', ['packaging_type'], unique=False)
    op.create_index(op.f('ix_packaging_boxes_shop_id'), 'packaging_boxes', ['shop_id'], unique=False)
    op.create_table('products',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_ref', name='uq_product_shop_external')
    )
    op.create_index(op.f('ix_products_shop_id'), 'products', ['shop_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sku', name='uq_variant_product_sku')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.add_column('order_items', sa.Column('product_variant_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('snapshot_weight_g', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('snapshot_length_mm', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('snapshot_width_mm', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('snapshot_height_mm', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('snapshot_title', sa.String(length=500), nullable=True))
    op.create_foreign_key('fk_order_items_product_variant_id', 'order_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('computed_parcel_weight_g', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('computed_parcel_length_mm', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('computed_parcel_width_mm', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('computed_parcel_height_mm', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('computed_packaging_box_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('parcel_override', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key('fk_orders_computed_packaging_box_id', 'orders', 'packaging_boxes', ['computed_packaging_box_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_computed_packaging_box_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'parcel_override')
    op.drop_column('orders', 'computed_packaging_box_id')
    op.drop_column('orders', 'computed_parcel_height_mm')
    op.drop_column('orders', 'computed_parcel_width_mm')
    op.drop_column('orders', 'computed_parcel_length_mm')
    op.drop_column('orders', 'computed_parcel_weight_g')
    op.drop_constraint('fk_order_items_product_variant_id', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'snapshot_title')
    op.drop_column('order_items', 'snapshot_height_mm')
    op.drop_column('order_items', 'snapshot_width_mm')
    op.drop_column('order_items', 'snapshot_length_mm')
    op.drop_column('order_items', 'snapshot_weight_g')
    op.drop_column('order_items', 'product_variant_id')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_products_shop_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_packaging_boxes_shop_id'), table_name='packaging_boxes')
    op.drop_index(op.f('ix_packaging_boxes_packaging_type'), table_name='packaging_boxes')
    op.drop_table('packaging_boxes')
    op.execute('DROP TYPE packaging_type')
    # ### end Alembic commands ###
