"""part1_partner_payouts

Revision ID: d48f7613dd60
Revises: f4d8b3a25c91
Create Date: 2026-05-16 11:50:01.252625
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48f7613dd60'
down_revision: Union[str, None] = 'f4d8b3a25c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_settlements',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=False),
    sa.Column('formula_type', sa.Enum('revenue_items_minus_fees', 'net_profit_product_only', name='partner_settlement_formula', create_constraint=True), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('computed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('percent > 0 AND percent <= 100', name='ck_partner_settlements_percent_range'),
    sa.CheckConstraint('period_end >= period_start', name='ck_partner_settlements_period_order'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_settlements_partner_shop', 'partner_settlements', ['partner_name', 'shop_id'], unique=False)
    op.create_index('ix_partner_settlements_shop_period', 'partner_settlements', ['shop_id', 'period_start'], unique=False)
    op.create_table('partner_payments',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_partner_payments_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['partner_settlements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_payments_partner_shop', 'partner_payments', ['partner_name', 'shop_id'], unique=False)
    op.create_index('ix_partner_payments_settlement', 'partner_payments', ['settlement_id'], unique=False)
    op.create_index('ix_partner_payments_shop_paid_at', 'partner_payments', ['shop_id', 'paid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_partner_payments_shop_paid_at', table_name='partner_payments')
    op.drop_index('ix_partner_payments_settlement', table_name='partner_payments')
    op.drop_index('ix_partner_payments_partner_shop', table_name='partner_payments')
    op.drop_table('partner_payments')
    op.drop_index('ix_partner_settlements_shop_period', table_name='partner_settlements')
    op.drop_index('ix_partner_settlements_partner_shop', table_name='partner_settlements')
    op.drop_table('partner_settlements')
    # ### end Alembic commands ###

    # Hand-edit: autogenerate does not drop the Postgres ENUM type. Drop
    # explicitly so a downgrade leaves the schema fully clean.
    sa.Enum(name='partner_settlement_formula').drop(op.get_bind(), checkfirst=True)
