"""add missing model columns (drift fix)

Revision ID: eade98846155
Revises: a1b2c3d4e5f6
Create Date: 2026-04-25 17:21:47.996846
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eade98846155'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('shipping_city', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('shipping_city_ref', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('shipping_warehouse_ref', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_city_ref', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_warehouse_ref', sa.String(length=100), nullable=True))
    op.add_column('shops', sa.Column('shopify_webhook_secret_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'shopify_webhook_secret_encrypted')
    op.drop_column('orders', 'shipping_warehouse_ref')
    op.drop_column('orders', 'shipping_city_ref')
    op.drop_column('customers', 'shipping_warehouse_ref')
    op.drop_column('customers', 'shipping_city_ref')
    op.drop_column('customers', 'shipping_city')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
